spring:
  datasource:
    # url: jdbc:mysql://${SPRING_MYSQL_DATASOURCE_HOST}:${SPRING_MYSQL_DATASOURCE_PORT}/${SPRING_MYSQL_DATASOURCE_DATABASE}
    url: jdbc:mysql://${SPRING_MYSQL_DATASOURCE_HOST}:${SPRING_MYSQL_DATASOURCE_PORT}/${SPRING_MYSQL_DATASOURCE_DATABASE}?useSSL=false&serverTimezone=UTC
    username: ${SPRING_MYSQL_DATASOURCE_USERNAME}
    password: ${SPRING_MYSQL_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      database: ${SPRING_MONGODB_DATABASE}
      username: ${SPRING_MONGODB_USERNAME}
      password: ${SPRING_MONGODB_PASSWORD}
      host: ${SPRING_MONGODB_HOST}
      port: ${SPRING_MONGODB_PORT}
      authentication-database: admin
logging:
  level:
    root: info