spring:
  application:
    name: realiza
  profiles:
    active: ${SPRING_ACTIVE_DATABASE:prod}
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
  logging:
    level:
      org:
        springframework:
          mail: DEBUG
          springframework: DEBUG
        apache:
          commons:
            mail: DEBUG
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USER}
    password: ${SPRING_RABBITMQ_PASSWORD}
server:
  port: 8080