spring:
  datasource:
    # url: jdbc:mysql://${SPRING_MYSQL_DATASOURCE_HOST}:${SPRING_MYSQL_DATASOURCE_PORT}/${SPRING_MYSQL_DATASOURCE_DATABASE}
    url: jdbc:mysql://${SPRING_MYSQL_DATASOURCE_HOST}:${SPRING_MYSQL_DATASOURCE_PORT}/${SPRING_MYSQL_DATASOURCE_DATABASE}?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${SPRING_MYSQL_DATASOURCE_USERNAME}
    password: ${SPRING_MYSQL_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 300000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
#  data:
#    mongodb:
#      database: ${SPRING_MONGODB_DATABASE}
#      username: ${SPRING_MONGODB_USERNAME}
#      password: ${SPRING_MONGODB_PASSWORD}
#      host: ${SPRING_MONGODB_HOST}
#      port: ${SPRING_MONGODB_PORT}
#      authentication-database: admin
gcp:
  storage:
    bucket: ${BUCKET_NAME}
logging:
  level:
    root: info