spring:
  application:
    name: realiza
  profiles:
    active: ${SPRING_ACTIVE_DATABASE:prod}
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USER}
    password: ${SPRING_RABBITMQ_PASSWORD}
    template:
      reply-timeout: 180000
server:
  address: 0.0.0.0
  port: ${PORT:8080}
